# Generated by Django 3.2.8 on 2021-10-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='musics',
        ),
        migrations.AddField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='playlist.playlist'),
            preserve_default=False,
        ),
    ]
