# Generated by Django 3.2.8 on 2021-11-12 06:38

import apps.playlist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20211023_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to=apps.playlist.models.get_upload_path),
        ),
    ]
